name: pri_stock_screener

channels:
  - default
  - anaconda
  - conda-forge
dependencies:
  - python>3.6
  - flask
  - flask-bootstrap
  - flask-wtf
  - pandas 
  - pip
  - pip:
    - yahoo_fin 
    - yfinance
    - TA-Lib
    - pandas-datareader
    - requests_html
